USE [master]
GO

/****** Object:  Database [bwpDB]    Script Date: 2024. 07. 07. 17:58:26 ******/
CREATE DATABASE [bwpDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bwpDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\bwpDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bwpDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\bwpDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bwpDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bwpDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bwpDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bwpDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bwpDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bwpDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [bwpDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bwpDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bwpDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bwpDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bwpDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bwpDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bwpDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bwpDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bwpDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bwpDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bwpDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bwpDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bwpDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bwpDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bwpDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bwpDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bwpDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bwpDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bwpDB] SET  MULTI_USER 
GO

ALTER DATABASE [bwpDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bwpDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bwpDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bwpDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bwpDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bwpDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [bwpDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [bwpDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [bwpDB] SET  READ_WRITE 
GO

